import test from 'node:test';
import assert from 'node:assert/strict';
import type {RendererAdapterResult} from '../src/renderer-adapter/index.js';
import {createUpstreamSupersessionContext, evaluateRenderFeedback, nextInternalReconciliation, unresolvedFittingFeedback} from '../src/feedback/index.js';

const version = {reference: 'test', version: '1.0.0' as const};
const base = (overrides: Partial<RendererAdapterResult> = {}): RendererAdapterResult => ({request_id: 'request-1', traceId: 'trace-1', contextId: 'context-1', lineage: [], presentationContractVersion: '1.0.0', templateId: 'cv-1', templateVersion: '1.0.0', designPolicyVersion: version, tokenSetVersion: version, rendererId: 'fake', rendererVersion: '1.0.0', artifact: {artifact_id: 'artifact-1', media_type: 'application/pdf', bytes: new Uint8Array([1])}, measurements: {page_count: 1, page_bounds: [], content_bounds: null, slot_bounds: [], overflow_height: 0, overflow_width: 0, affected_regions: [], constraint_measurements: []}, failure: null, ...overrides});
const evaluate = (result: RendererAdapterResult, attempt = 1, densityAdjustmentApplied = false) => evaluateRenderFeedback(result, {presentationRunId: 'run-1', attempt, createdAt: '2026-09-09T00:00:00Z', densityAdjustmentApplied});

test('evaluates FIT and preserves correlation and versions', () => { const feedback = evaluate(base()); assert.equal(feedback.status, 'FIT'); assert.equal(feedback.request_id, 'request-1'); assert.equal(feedback.traceId, 'trace-1'); assert.equal(feedback.contextId, 'context-1'); assert.equal(feedback.designPolicyVersion.reference, 'test'); });
test('evaluates density-adjusted FIT', () => assert.equal(evaluate(base(), 2, true).status, 'FIT_WITH_DENSITY_ADJUSTMENT'));
test('evaluates constraint violation before overflow', () => { const feedback = evaluate(base({measurements: {...base().measurements!, overflow_height: 10, constraint_measurements: [{constraint_id: 'max-height', allowed_boundary: 100, measured_value: 120}]}})); assert.equal(feedback.status, 'CONSTRAINT_VIOLATION'); assert.equal(feedback.diagnostics[0]?.diagnostic_type, 'CONSTRAINT_VIOLATION'); });
test('evaluates multi-region vertical and horizontal overflow', () => { const feedback = evaluate(base({measurements: {...base().measurements!, overflow_height: 20, overflow_width: 5, affected_regions: ['experience', 'skills']}})); assert.equal(feedback.status, 'OVERFLOW'); assert.equal(feedback.diagnostics[0]?.diagnostic_type, 'OVERFLOW'); });
test('evaluates backend failure as RENDER_FAILED', () => { const feedback = evaluate(base({artifact: null, measurements: null, failure: {code: 'BACKEND_TIMEOUT', stage: 'RENDER', retryable: true, message: 'sanitized'}})); assert.equal(feedback.status, 'RENDER_FAILED'); assert.equal(feedback.diagnostics[0]?.diagnostic_type, 'RENDER_FAILED'); });
test('bounds internal visual reconciliation at three attempts', () => { const first = evaluate(base({measurements: {...base().measurements!, overflow_height: 20}})); const second = nextInternalReconciliation(first); assert.equal(second?.attempt, 2); const third = nextInternalReconciliation({...first, request_id: 'request-2', attempt: 3}); assert.equal(third, null); assert.equal(unresolvedFittingFeedback({...first, request_id: 'request-3', attempt: 3}).status, 'FIT_FAILED_UNRESOLVABLE'); });
test('keeps upstream supersession distinct and bounded', () => { const context = createUpstreamSupersessionContext('request-2', 'presentation-2', 'request-1', 'presentation-1', 1, [], version); assert.equal(context.supersedesRequestId, 'request-1'); assert.equal(context.lineage[0]?.transform_id, 'supersedes_request_id'); assert.throws(() => createUpstreamSupersessionContext('request-4', 'presentation-4', 'request-3', null, 4, [], version), /depth/); });
